#
# This workflow will run all the normal static tests (linting, unit, etc.).
#

name: test

on:
  push:
    branches: [ 'feature/*' ]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
      env:
        STAGE: local
